### ISSUE TITLE
More better DV integration

### ISSUE THREAD

**Issue by chaosphere2112** [ACME-OUI/acme-web-fe#181]
We want to make it so the dashboard can directly embed diagnostics viewer output. This should be pretty doable by doing basically what the Diagnostics Viewer does: embedding iframes of a couple of views.

This path:

```
"/output/" + dataset + "/" + package + "/"
```

will get you the index page for the package. From there, you need to open paths inside the package (by appending them to the end of the URL), like so:

```
/output/2/amwg/set_5/index.html
```

I'll try and simplify this somewhat for your consumption, so we can just have one shared view that we both can access. This will probably need to be broken into a few subtasks, which I'll open separately and link to from here:
- [ ] ESGF Login for Dashboard (#182)
- [ ] ESGF Login for Diagnostics Viewer (ESGF/DiagnosticsViewer#1)
- [ ] Embeddable View for DiagnosticsViewer (ESGF/DiagnosticsViewer#5)
- [ ] Dashboard pane that directly opens DV pages (We'll just track this one here)

**Comment by sterlingbaldwin** [comment]
+1
